### ISSUE TITLE
[BUG] Some folders and files are missing on mount.

### ISSUE THREAD

**Issue by ShapeShifter499** [seiferma/splitviewfuse#11]
I have a 4tb drive of which 1tb is all used up. When I mount this drive under 'splitviewfuse' in a different directory, most folders and files will show. But a lot of folders and files don't show up at all and I'm not sure why. I have no idea where to start on diagnosing the issue.  I do know some of the folders and files inside the drive have been encrypted with eCryptFS and the drive itself is formatted ext4.  This issue does not seem to effect the actual files only the 'split' view of them.  I have not tried unionviewfuse to see if the issue is also there. 

This is on a Arch Linux 64bit system, I have python2 installed.

**Comment by ShapeShifter499** [comment]
Is this project dead?

**Comment by seiferma** [comment]
It isn't dead. But it isn't a commercial project that I do for living.

Unfortunately, I did not have enough time to implement the logging facility. As a first try, you could use the following mount options and check that there are not error messages appearing when using the fuse mount:
`-o nothreads=True,foreground=True`

Could you give me a few examples of file names that do not appear splitted?

I will have a look at the code in the next days and check if I correctly use the file system APIs with respect to numerical limitations of the result objects.

**Comment by ShapeShifter499** [comment]
I'll upload a log with those flags passed to fuse when I get back to my computer later today or tomorrow. 

Files in question, there are quite a lot. But one particular set of files is the backup of my linux home directory. It's stored on the EXT4 formatted drive encrypted with eCryptFS. It doesn't matter if I mount the directory decrypted before I use splitviewfuse or just splitviewfuse the encrypted files. In both cases the directory appears completely empty.

**Comment by ShapeShifter499** [comment]
I ran the following command  and there is no output in the terminal even after I escape out with ctrl+c. I browsed to the same parts of the file structure that appear empty in splitviewfuse.

```
sudo splitviewfuse /run/media/raansu/2b165e4f-8bbe-4fe1-81dd-653be4df6859/ /mnt/split/ -o segmentsize=10737418240,allow_other,nothreads=True,foreground=True
```

**Comment by seiferma** [comment]
I pushed a new version to pypi that includes some logging facilities. Could you add the option `loglevel=debug` to the mount options as described in the [README](https://github.com/seiferma/splitviewfuse/blob/master/README.rst) and share the log with me?

**Comment by ShapeShifter499** [comment]
Ok I was able to get a log from the latest code you posted, here it is below. 

[splitview-log.txt](https://github.com/seiferma/splitviewfuse/files/532264/splitview-log.txt)

I ran the following command and then navigated to the same home directory backup which still appears empty inside of the split view.

```
sudo splitviewfuse /run/media/raansu/2b165e4f-8bbe-4fe1-81d653be4df6859/ /mnt/split/ -o segmentsize=10737418240,allow_other,loglevel=debug,logfile=/home/raansu/splitview.log,debug,nothreads=True,foreground=True
```

**Comment by ShapeShifter499** [comment]
@seiferma I'm sorry if you are busy, I do not want to rush you. I just want to know where you are on this issue.

**Comment by seiferma** [comment]
Sorry, I basically had not time to look into this at all. What I see from the logs are a few permission denied errors and a directory not found error. Do you try to list the contents of the directory `/encrypted/750gb-open/ArchLinuxY40-80/unzipped/AntergosRoot/home/raansu`? If so, does the issue still occur if you remove `PlayOnLinux\'s virtual drives`? Are there any symlinks involved?

**Comment by ShapeShifter499** [comment]
Ok so I looked into it and  the file "PlayOnLinux\'s virtual drives"  is a broken symlink that used to link to "/home/raansu/.PlayOnLinux//wineprefix/" 

 which has changed to "/mnt/split/encrypted/750gb-open/ArchLinuxY40-80/unzipped/AntergosRoot/home/raansu/.PlayOnLinux/wineprefix/"  Since I did copy my whole home directory out of the original location.

When I removed the broken symlink file it automatically worked again when I mounted the directory with splitviewfuse. I was able to view all the files and folders under my backed up home directory in the split view. It would seem there needs to be better handling when there is a broken symlink, maybe treat a broken symlink as a zero byte file?

**Comment by ShapeShifter499** [comment]
I did some further testing, I'm fairly certain that broken symlinks are the reason why splitviewfuse fails to display some files and folders. If a broken symlink file sits at the root of a directory then all files and folders in that directory will fail to display. Like I said before, there needs to be broken symlink support.

**Comment by seiferma** [comment]
Thanks for verifying the cause of this issue. Indeed, the assumption for resolving symlinks was that the target exists. Anyway, representing symlinks as regular files might not be a perfect solution. But changing this would require some considerable effort.

Threfore, I will add test cases and according error handling for broken symlinks but still represent them as regular files.

**Comment by ShapeShifter499** [comment]
So the current workaround is to make sure there are no broken symlinks right?

**Comment by seiferma** [comment]
In general, it is a good idea to fix issues in the directory structure, yes.

I pushed a new version that should address the issue. Broken symlinks are still shown in the directory listing but any operation on them fails with a file not found error. This should be as close as possible to the handling of broken symlinks other filesystems.

If you are still facing issues with broken symlinks, please give me a quick note.

**Comment by ShapeShifter499** [comment]
@seiferma Thank you for the update. I just tested it and it works fine as far as I can tell. All broken symlinks are ignored and do not show up at all in the split view of the files and folders.
